version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: giveme_backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - media_files:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG:-True}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5432}
      - SUPABASE_ACCESS_KEY=${SUPABASE_ACCESS_KEY}
      - SUPABASE_SECRET_KEY=${SUPABASE_SECRET_KEY}
      - SUPABASE_CUSTOM_DOMAIN=${SUPABASE_CUSTOM_DOMAIN}
      - SUPABASE_ENDPOINT_URL=${SUPABASE_ENDPOINT_URL}
      - SUPABASE_BUCKET_NAME=${SUPABASE_BUCKET_NAME}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: giveme_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
    - CHOKIDAR_USEPOLLING=true    # força o React/Vite a detectar mudanças
    - WATCHPACK_POLLING=true      
    - VITE_API_URL=http://localhost:8000
    - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
    - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    - HOST=0.0.0.0
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0

volumes:
  media_files: